### ISSUE TITLE
Records in Portrait even though iPad (8th Generation) simulator is in Landscape

### ISSUE THREAD

**Issue by pdxplaid** [AvdLee/RocketSimApp#90]
**Describe the bug**
if the iPad simulator is in landscape and I press record, the video comes out in portrait mode and has to be rotated using quicktime after the fact.

**To Reproduce**
1. open something in the iPad (8th Generation) simulator
2. rotate the simulator to landscape
3. press record in RocketSim
4. record for some time - a couple of seconds will do
5. stop recording.
6. look at the recorded video.

**Expected behavior**
I expect the video to be in the same orientation as the simulator.

**Desktop (please complete the following information):**
 - OS: macOS lastest ( 11.2.3 )
 - Version 11.2.3
 - iPad (8th Generation) simulator (Version 12.4 (940.20)  SimulatorKit 597.13.0.1. CoreSimulator 732.18.6

**Additional context**
thanks

**Comment by AvdLee** [comment]
@pdxplaid thanks for reaching out! Which version of RocketSim are you using?

**Comment by pdxplaid** [comment]
3.4.3

i'm happy to send you diagnostics if that'll help any.

thanks
--->PAul

**Comment by AvdLee** [comment]
@pdxplaid yes, please. That would definitely help!

**Comment by AvdLee** [comment]
This is fixed in the upcoming release! Thanks for reporting 🙂

**Comment by pdxplaid** [comment]
Perfect! Thanks!

**Comment by pdxplaid** [comment]
:) today I noticed that in version 4.0.2 on my Mac m1 mini, when the iPad (8th Generation) simulator is in landscape with the home button on the right side, the video comes out upside down!!! when the home button is on the left side, the video comes out fine... So the bug is not completely fixed, but it's closer. at least it's recording in landscape...

**Comment by AvdLee** [comment]
@pdxplaid Yes, I'm very aware of that problem! Unfortunately, I can't read out landscapeLeft or landscapeRight. Therefore, this issue is very hard to fix.

I hope you can use that workaround!

**Comment by pdxplaid** [comment]
no worries! I can flip the simulator into the right direction when I need to record. I love rocket sim, and I find most of your posts very useful (when they aren't way over my head!). Learning Swift is fun/hard. :)

Thanks!
--->PAul
